name: agni
channels:
  - conda-forge

dependencies:
  # ——————————————————————————
  # 1) Python
  #——————————————————————————
  # lock to the same Python range you test against
  - python>=3.10,<3.12

  # ——————————————————————————
  # 2) Conda‑forge packages
  #——————————————————————————
  - numpy>=1.20.0,<=2.2.4
  - scipy>=1.7.0,<=1.15.2
  - matplotlib>=3.7.3,<=3.10.1
  - h5py>=3.0.0,<=3.13.0
  - netcdf4>=1.5.4,<=1.7.2
  - scikit-image<=0.25.1
  - colorama<=0.4.6

  # ——————————————————————————
  # 3) pip and its extras
  #——————————————————————————
  - pip

  - pip:
    # JAX (will pull in ml_dtypes, opt_einsum, jaxlib, …)
    - jax[cpu]>=0.4.24,!=0.4.36,<=0.5.3

    # your own pip‑only libs
    - interpax>=0.3.3,<=0.3.6
    - termcolor<=3.0.1

    # test suite
    - pytest
    - pytest-xdist
    - pytest-cov
